[build]
builder = "DOCKERFILE"
dockerfilePath = "docker/Dockerfile"
watchPatterns = ["docker/Dockerfile", ".trigger-deploy", "railway.toml", "config/caddy/*.Caddyfile"]

[deploy]
numReplicas = 1
sleepApplication = true
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 2