name: Request to add proxyparty to your (sub)domain
description: >-
  Use this form to request to add your (sub)domain into our Caddy configuration. You can
  also use this to update your configuration if you prefer not to send patches.
assignees: [ajhalili2006]
title: "[<new-domain|update-config>]: Request to add/update config for <domain here>"
body:
  - type: input
    id: domain
    attributes:
      label: Domain to be added
      description: >-
        If it is a subdomain, please include both the subdomain and the base
        domain. No protocols please.
      placeholder: "[sub].domain.tld"
    validations:
      required: true
  - type: input
    id: target
    attributes:
      label: Target URL
      description: >-
        Where do we want to redirect or proxy that domain into? If you're redirecting
        in bulk, please note them in the reason field below. If you're not changing the
        redirects, please type `Not Applicable`.
      placeholder: https://target-url.tld/owo
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Please describe why you need this service
      description: >-
        We review your request before we add into our configuration to prevent
        abuse. If it is intended for `proxyparty.hackclub.com`, we'll ask you to
        file a issue there instead.
      value: |-
        Your reason goes here, just replace this text with a real one.

        <!-- delete the text below this line, including this if not neeeded -->
        **Additional (sub)domain redirect routes**:
        - sub.domain.tld: https://target-url.tld/owo
        - domain-two.tld: https://chaos.dev

        **Paths with target URL overrides**:
        - /path1: https://another-url.tld/todo
        - /path2: https://why.dev/chaos
        - domain-two.tld/gtwscar: https://hermitcraft.com/scar
        <!-- delete the text above this line, including this if not neeeded -->
    validations:
      required: true
  - type: checkboxes
    id: options
    attributes:
      label: Anything else?
      description: >-
        If you tick the third or fourth checkbox, follow the instructions on the template
        text above.
      options:
        - label: I need to proxy into the target URL instead of a simple redirect.
          required: false
        - label: Redirect all paths on the source URL
          required: false
        - label: I need to redirect some paths to other target URLs.
          required: false
        - label: I am redirecting/proxying more than one (sub)domain.
          required: false
  - type: markdown
    attributes:
      value: |-
        ---
        _This template was generated with [Issue Forms Creator](https://issue-forms-creator.netlify.app)_
