#!/usr/bin/env bash
set -e
CONFIG_PATH=${CONFIG_PATH:-"./config/caddy/Caddyfile"}
CADDY_ADMIN=${CADDY_ADMIN:-"100.77.60.119:20241"}

dotenvx run -f .env.production -- caddy reload \
  --config "${CONFIG_PATH}" \
  --address "${CADDY_ADMIN}"
