#!/usr/bin/env bash
set -e
CONFIG_PATH=${CONFIG_PATH:-"./config/caddy/gcp/Caddyfile"}
CADDY_ADMIN=${CADDY_ADMIN:-"100.125.197.28:20241"}

dotenvx run -f .env.production -- caddy reload \
  --config "${CONFIG_PATH}" \
  --address "${CADDY_ADMIN}"