#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
PARENT_DIR="$(dirname "$SCRIPT_DIR")"

echo "Pulling updates from the repository..."
git -C "$PARENT_DIR" pull hub main

echo "Reloading Caddy with new configuration..."
CADDY_ADMIN="localhost:20241" CONFIG_PATH="$PARENT_DIR/config/caddy/Caddyfile" "$SCRIPT_DIR/apply"
