#!/usr/bin/env bash
# This shell script should be only ran by root, since we're
# copying configuration files into /etc directories. Please
# thread lightly on this.

if [ $EUID != "0" ]; then
  echo "This script should be ran by root!"
  exit 1
fi

set -xe
CADDY_CONFIG_HOME=${CADDY_CONFIG_HOME:-"/var/caddy/src"}

cp "${CADDY_CONFIG_HOME}/config/sudo_caddy.conf" "/etc/sudoers.d/caddy.conf"

cp "${CADDY_CONFIG_HOME}/config/systemd/caddy-docker.service" "/etc/systemd/system/caddy-docker.service"
cp "${CADDY_CONFIG_HOME}/config/systemd/caddy.service" "/etc/systemd/system/caddy.service"
systemctl daemon-reload

if [[ ${1} == "docker" ]]; then
  systemctl disable caddy.service --now
  systemctl enable caddy-docker.service --now
else
  systemctl enable caddy.service --now
  systemctl disable caddy-docker.service --now
fi
