#!/usr/bin/env bash
# This shell script should be only ran by root, since we're
# copying configuration files into /etc directories. Please
# thread lightly on this.

if [ $EUID != "0" ]; then
  echo "This script should be ran by root!"
  exit 1
fi

set -xe
CADDY_CONFIG_HOME=${CADDY_CONFIG_HOME:-"/var/caddy/src"}

cp "${CADDY_CONFIG_HOME}/config/sudo_caddy.conf" "/etc/sudoers.d/caddy"

cp "${CADDY_CONFIG_HOME}/config/systemd/caddy.service" "/etc/systemd/system/caddy.service"
systemctl daemon-reload

if [[ ${FF_ONLY_RELOAD_CONFIG} != "" ]]; then
  systemctl reload caddy.service
else
  systemctl enable caddy.service --now
fi
